CREATE DATABASE IF NOT EXISTS corinthians_site
  DEFAULT CHARACTER SET utf8mb4
  DEFAULT COLLATE utf8mb4_unicode_ci;

USE corinthians_site;

CREATE TABLE IF NOT EXISTS torcedores (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nome VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL UNIQUE,
  cidade VARCHAR(255) NOT NULL,
  jogador_favorito VARCHAR(255),
  criado_em DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS idolos (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nome VARCHAR(255) NOT NULL,
  posicao VARCHAR(255) NOT NULL,
  periodo VARCHAR(255) NOT NULL,
  descricao TEXT NOT NULL,
  ordem INT NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS historia (
  id INT AUTO_INCREMENT PRIMARY KEY,
  ano INT NOT NULL,
  titulo VARCHAR(255) NOT NULL,
  descricao TEXT NOT NULL
);
